version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: gradle dependencies

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}
      
      # run tests!
      - run: gradle test
      
      - run:
          name: Save test results
          command: |
            mkdir -p ~/junit/
            find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/junit/ \;
            cp -r build/reports/tests/test/ ~/junit
          when: always
      - store_test_results:
          path: ~/junit
      - store_artifacts:
          path: ~/junit

      - run: gradle clean build
      - run: 
          name: save jar
          command: |
            mkdir -p ~/result
            cp build/libs/springBoot-0.0.1-SNAPSHOT.jar ~/result/springBoot.jar
      - store_artifacts:
          path: ~/result

      
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Install Docker client
          command: |
            docker --version
      
      - run:
          name: docker build, run, test
          command: |
            docker build -t "springboot" .
            echo "build ok."
            docker run -d -p 8086:8086 --name nickSpringBoot springboot
            echo "run..."
            sleep 10
            curl --retry 10 --retry-delay 5 -v http://localhost:8086
    